export const APP_ROUTES = [
  {
    path: "/app/dashboard",
    label: "Dashboard",
    icon: "LayoutDashboard",
    roles: ["OFFICER", "ADMIN"],
    inSidebar: true,
  },
  {
    path: "/app/scan",
    label: "Scan Document",
    icon: "ScanLine",
    roles: ["SUBMITTER", "OFFICER"],
    inSidebar: true,
  },
  {
    path: "/app/submissions",
    label: "My Submissions",
    icon: "FileText",
    roles: ["SUBMITTER", "OFFICER", "ADMIN"],
    inSidebar: true,
  },
  {
    path: "/app/submissions/:id",
    label: "Submission Detail",
    roles: ["SUBMITTER", "OFFICER", "ADMIN"],
    inSidebar: false,
  },
  {
    path: "/app/submissions/:id/face-verify",
    label: "Live Face Verification",
    roles: ["SUBMITTER", "OFFICER", "ADMIN"],
    inSidebar: false,
  },
  {
    path: "/app/reviews/queue",
    label: "Review Queue",
    icon: "ShieldAlert",
    roles: ["OFFICER", "ADMIN"],
    inSidebar: true,
  },
  {
    path: "/app/reviews/mine",
    label: "My Decisions",
    icon: "History",
    roles: ["OFFICER"],
    inSidebar: true,
  },
  {
    path: "/app/reviews/:documentId",
    label: "Review Detail",
    roles: ["OFFICER", "ADMIN"],
    inSidebar: false,
  },
  {
    path: "/app/admin/users",
    label: "User Management",
    icon: "Users",
    roles: ["ADMIN"],
    inSidebar: true,
  },
  {
    path: "/app/admin/audit",
    label: "Audit Logs",
    icon: "Activity",
    roles: ["ADMIN"],
    inSidebar: true,
  },
  {
    path: "/app/admin/stats",
    label: "Analytics & Stats",
    icon: "BarChart3",
    roles: ["ADMIN"],
    inSidebar: true,
  },
  {
    path: "/app/profile",
    label: "Profile",
    icon: "User",
    roles: ["SUBMITTER", "OFFICER", "ADMIN"],
    inSidebar: true,
  },
];
