services:
  postgres:
    image: postgres:16-alpine
    container_name: satyascan_postgres
    restart: always
    environment:
      POSTGRES_USER: satyascan
      POSTGRES_PASSWORD: satyascan_pass
      POSTGRES_DB: satyascan_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U satyascan -d satyascan_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: satyascan_adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
